# Generated by Django 4.1 on 2022-09-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_profile_proile_img_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proile_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
